In [3]:
import pandas as pd
import numpy as np

In [4]:
df_a = pd.read_csv("../data/ehr_system_A.csv")

df_a.head()

,patient_id,encounter_id,birth_date,gender,encounter_date,condition,procedure,lab_result,value
0,1,E001,1980-05-12,M,2025-01-10,Hypertension,Blood Pressure Check,SBP,140.0
1,2,E002,1975-08-20,F,2025-01-12,Diabetes,Glucose Test,Glucose,180.0
2,3,E003,1990-03-15,M,2025-01-15,Asthma,Spirometry,FEV1,2.5
3,4,E004,1985-11-30,F,2025-01-18,Hypertension,Blood Pressure Check,SBP,150.0
4,5,E005,2000-07-22,M,2025-01-20,Diabetes,Glucose Test,Glucose,200.0

In [5]:
df_a = pd.read_csv("../data/ehr_system_A.csv")
df_a.head()

,patient_id,encounter_id,birth_date,gender,encounter_date,condition,procedure,lab_result,value
0,1,E001,1980-05-12,M,2025-01-10,Hypertension,Blood Pressure Check,SBP,140.0
1,2,E002,1975-08-20,F,2025-01-12,Diabetes,Glucose Test,Glucose,180.0
2,3,E003,1990-03-15,M,2025-01-15,Asthma,Spirometry,FEV1,2.5
3,4,E004,1985-11-30,F,2025-01-18,Hypertension,Blood Pressure Check,SBP,150.0
4,5,E005,2000-07-22,M,2025-01-20,Diabetes,Glucose Test,Glucose,200.0

In [6]:
df_a.info()
df_a.describe()
df_a.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      5 non-null      int64
 1   encounter_id    5 non-null      str
 2   birth_date      5 non-null      str
 3   gender          5 non-null      str
 4   encounter_date  5 non-null      str
 5   condition       5 non-null      str
 6   procedure       5 non-null      str
 7   lab_result      5 non-null      str
 8   value           5 non-null      float64
dtypes: float64(1), int64(1), str(7)
memory usage: 492.0 bytes

patient_id        0
encounter_id      0
birth_date        0
gender            0
encounter_date    0
condition         0
procedure         0
lab_result        0
value             0
dtype: int64

In [7]:
df_b = pd.read_csv("../data/ehr_system_B.csv")

df_b.head()

,patient_id,encounter_id,birth_date,gender,encounter_date,condition,procedure,lab_result,value
0,1,E101,1980-05-12,M,2025-02-05,Hypertension,Blood Pressure Check,SBP,145.0
1,2,E102,1975-08-20,F,2025-02-10,Diabetes,Glucose Test,Glucose,190.0
2,6,E103,1988-09-10,F,2025-02-12,Asthma,Spirometry,FEV1,2.8
3,7,E104,1995-04-18,M,2025-02-15,Hypertension,Blood Pressure Check,SBP,135.0

In [8]:
df_combined = pd.concat([df_a, df_b], ignore_index=True)

df_combined.head()

,patient_id,encounter_id,birth_date,gender,encounter_date,condition,procedure,lab_result,value
0,1,E001,1980-05-12,M,2025-01-10,Hypertension,Blood Pressure Check,SBP,140.0
1,2,E002,1975-08-20,F,2025-01-12,Diabetes,Glucose Test,Glucose,180.0
2,3,E003,1990-03-15,M,2025-01-15,Asthma,Spirometry,FEV1,2.5
3,4,E004,1985-11-30,F,2025-01-18,Hypertension,Blood Pressure Check,SBP,150.0
4,5,E005,2000-07-22,M,2025-01-20,Diabetes,Glucose Test,Glucose,200.0

In [9]:
df_combined.info()
df_combined.duplicated().sum()
df_combined['patient_id'].nunique()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      9 non-null      int64
 1   encounter_id    9 non-null      str
 2   birth_date      9 non-null      str
 3   gender          9 non-null      str
 4   encounter_date  9 non-null      str
 5   condition       9 non-null      str
 6   procedure       9 non-null      str
 7   lab_result      9 non-null      str
 8   value           9 non-null      float64
dtypes: float64(1), int64(1), str(7)
memory usage: 780.0 bytes

7

In [10]:
# Sort by latest encounter
df_combined['encounter_date'] = pd.to_datetime(df_combined['encounter_date'])
df_sorted = df_combined.sort_values(by='encounter_date')

# Keep latest record per patient
df_patient_latest = df_sorted.groupby('patient_id').last().reset_index()

df_patient_latest.head()

,patient_id,encounter_id,birth_date,gender,encounter_date,condition,procedure,lab_result,value
0,1,E101,1980-05-12,M,2025-02-05,Hypertension,Blood Pressure Check,SBP,145.0
1,2,E102,1975-08-20,F,2025-02-10,Diabetes,Glucose Test,Glucose,190.0
2,3,E003,1990-03-15,M,2025-01-15,Asthma,Spirometry,FEV1,2.5
3,4,E004,1985-11-30,F,2025-01-18,Hypertension,Blood Pressure Check,SBP,150.0
4,5,E005,2000-07-22,M,2025-01-20,Diabetes,Glucose Test,Glucose,200.0

### Shared Care Record Creation

Data from multiple EHR systems was integrated to create a unified patient-level dataset.

For each patient, the most recent encounter was selected to simulate a shared care record, enabling a single, trusted view of patient data across systems.

This step demonstrates the core concept of a platform-based EHR architecture.

In [12]:
df_patient_latest.to_csv("../outputs/shared_care_record.csv", index=False)

In [13]:
df_combined.to_csv("../outputs/integrated_ehr_dataset.csv", index=False)

### Key Insight

Integrating data from multiple EHR systems revealed that patient information is distributed across sources, but can be unified into a single, reliable record.

This unified dataset enables downstream applications such as clinical decision support, risk prediction, and AI-driven healthcare analytics.